# Generated by Django 5.1.1 on 2024-11-06 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='data_added',
            new_name='dte_added',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='data_added',
            new_name='dte_added',
        ),
    ]
